name: MLOps CD
on:
  workflow_run:
    workflows: ["MLOps training"]
    types: [requested, completed]
    branches:
      - "main"
  workflow_dispatch:

jobs: 
  Model_CI_Pipeline:
    runs-on: [self-hosted, local-linux]
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container: mcr.microsoft.com/mlops/python:latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Test vars
      run: |
        echo "Name or Id of the workflow"
        echo ${{ github.event.workflow_run.workflow_id }}
        echo "********"
        echo ${{ github.event.workflow_run.conclusion }}
        echo "********"
        
    - name: Download artifact from workflow_run event
      uses: dawidd6/action-download-artifact@v2
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        run_id: ${{ github.event.workflow_run.workflow_id }}
        name: MLdrop

    - name: Download artifact manual
      uses: dawidd6/action-download-artifact@v2
      if: ${{ github.event.workflow_run.conclusion == '' }}
      with:
        workflow: mlops-CI.yml
        name: MLdrop

    - name: List items
      run: |
        ls
        ls MLdrop

    - name: Parse Json for Model Name and Version
      run: |
        # Print JSON
        cat MLdrop/model.json | jq '.'
        # Set model name and version variables
        MODEL_NAME=$(jq -r '.name' MLdrop/model.json)
        MODEL_VERSION=$(jq -r '.version' MLdrop/model.json)

        echo "Model Name: $MODEL_NAME"
        echo "Model Version: $MODEL_VERSION"

        # Set environment variables

        echo $MODEL_NAME >> $GITHUB_ENV
        echo $MODEL_VERSION >> $GITHUB_ENV



  
