name: MLOps training
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs: 
  MLOps-GitHub-Actions:
    runs-on: [self-hosted, local-linux]
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script Show
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show

    - name: Azure CLI script Logout
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear