name: MLOps training
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs: 
  
  Model_CI_Pipeline:
    runs-on: [self-hosted, local-linux]
    container: mcr.microsoft.com/mlops/python:latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Copy env.example to .env for testing
      run: |
        cp .env.example .env
        ls
    
    - name: Run lint tests
      run: |
        flake8 --output-file=lint-testresults.xml --format junit-xml

    - name: Run unit tests
      run: |
        python -m pytest . --cov=diabetes_regression --cov-report=html --cov-report=xml --junitxml=unit-testresults.xml

    - name: Upload coverage results
      uses: actions/upload-artifact@v3
      with:
        name: drop
        path: coverage.xml  
        retention-days: 1

    - name: 'Publish Azure Machine Learning Pipeline'
      run: |
        set -e # fail on error
        export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        # Invoke the Python building and publishing a training pipeline
        python -m ml_service.pipelines.diabetes_regression_build_train_pipeline