name: MLOps training
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs: 
  
  Init_Workflow:
    runs-on: [self-hosted, local-linux]
    steps:
    - name: Set the value
      id: step_one
      run: |
        echo "$action_state" # This will output 'NA'
        echo "action_state=yellow" >> $GITHUB_ENV  



  Model_CI_Pipeline:
    needs: Init_Workflow
    runs-on: [self-hosted, local-linux]
    container: mcr.microsoft.com/mlops/python:latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}" # This will output 'yellow'

    - name: Use the value v2
      id: step_three
      run: |
        echo "$action_state" # This will output 'yellow'

    - name: Azure CLI script Show
      run: |
        az account show
    
    - name: Azure CLI script Log out
      run: |
        az logout
        az cache purge
        az account clear

