name: MLOps training
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs: 
  MLOps-GitHub-Actions:
    runs-on: [self-hosted, local-linux]
    container: mcr.microsoft.com/mlops/python:latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: main
    

